import { createI18n } from "vue-i18n";

export const messages = {
  "zh-CN": {
    common: { retry: "重试", cancel: "取消", unknown: "未知", repository: "仓库" },
    nav: { registries: "REGISTRIES", addRegistry: "添加 Registry", addFirst: "添加第一个 Registry", settings: "连接设置", globalSettings: "全局代理设置", language: "切换语言", moveUp: "上移", moveDown: "下移" },
    connection: { checking: "检测中", connected: "已连接", failed: "连接异常" },
    welcome: { eyebrow: "PRIVATE REGISTRY MANAGER", title: "连接你的镜像仓库", body: "集中查看仓库、标签与 Manifest，并安全执行镜像清理。" },
    repositories: { eyebrow: "CATALOG", title: "仓库", search: "搜索仓库", loading: "正在加载仓库", error: "无法读取 Catalog", empty: "没有找到仓库", publicEmpty: "添加完整仓库名称后即可浏览镜像", add: "添加仓库", removeHint: "从 Kaven Docker 列表中移除", removed: "已从 Kaven Docker 中移除仓库 {repository}", addTitle: "添加镜像仓库", addMethod: "添加方式", discoverMode: "自动查找", manualMode: "手动输入", namespace: "用户或命名空间", discover: "立即查找仓库", additionalNames: "其他仓库名称（可选）", fullNames: "完整仓库名称", namesPlaceholder: "api\nweb\nworker", addHint: "输入命名空间后会自动查找仓库。也可每行输入一个额外名称，或直接输入 {example} 这样的完整名称。", manualHint: "每行输入一个完整名称，也可用逗号分隔。例如：{example}。无需包含 Registry 地址、Tag 或 Digest。", discoveryUnsupported: "此 Registry 不支持按命名空间自动查找，请切换到手动输入。", discovered: "已找到 {count} 个仓库", preview: "待添加仓库", selected: "已选择 {count} 个", selectAll: "全选", deselectAll: "取消全选", saveCount: "添加 {count} 个", required: "请至少选择一个仓库", addedMany: "已添加 {count} 个仓库" },
    discoveryErrors: { invalidNamespace: "用户或命名空间无效", repositoryDiscoveryUnsupported: "此 Registry 不支持自动查找仓库", repositoryDiscoveryAuthRequired: "GHCR 自动查找需要配置具有 read:packages 权限的 GitHub Token", repositoryDiscoveryFormat: "仓库查找接口返回了无效数据" },
    registryOrderErrors: { invalidRegistryOrder: "Registry 排序无效，请刷新后重试" },
    tags: { eyebrow: "VERSIONS", title: "标签", search: "搜索标签", loading: "正在加载标签", error: "无法读取 Tags", selectRepository: "选择一个仓库", empty: "没有找到标签" },
    details: { loading: "正在解析 Manifest", error: "Manifest 加载失败", eyebrow: "IMAGE DETAILS", more: "更多操作", copyPull: "复制 Pull 命令", reference: "镜像引用", imageName: "镜像名", copyImageName: "复制镜像名", tag: "Tag", copyTag: "复制 Tag", fullReference: "完整引用", copyReference: "复制完整镜像引用", imageSize: "镜像大小", platforms: "平台", platformCount: "{count} 个平台", created: "创建时间", manifest: "Manifest", digest: "Digest", copyDigest: "复制 Digest", mediaType: "Media type", layers: "Layers", labels: "Labels", selectTitle: "选择一个镜像标签", selectBody: "Manifest、平台与层信息会显示在这里。" },
    danger: { title: "删除 Manifest", hint: "删除后需要服务端垃圾回收才能释放存储空间。", action: "删除" },
    form: { eyebrow: "REGISTRY CONNECTION", editTitle: "编辑连接", addTitle: "添加 Registry", displayName: "显示名称", address: "Registry 地址", auth: "认证方式", anonymous: "匿名", basic: "用户名密码", username: "用户名", password: "密码", keepPassword: "留空以保留原密码", enterPassword: "输入密码", caPath: "自定义 CA 文件路径（可选）", allowHttp: "允许不安全 HTTP", allowHttpHint: "仅用于可信内网环境", skipTls: "跳过 TLS 证书验证", skipTlsHint: "不建议在生产环境启用", timeout: "请求超时", seconds: "秒", uploadChunkSize: "上传分块大小", uploadChunkSizeHint: "较大的分块可减少目标 Registry 的状态文件写入次数，范围 1–256 MiB。", remove: "移除连接", save: "保存连接" },
    proxy: { eyebrow: "NETWORK SETTINGS", globalTitle: "代理配置", globalDefault: "全局默认代理", applyDefault: "应用默认值", registryMode: "代理设置", followGlobal: "跟随全局设置", direct: "直连（不使用代理）", savedProfiles: "已保存的代理", legacyCustom: "原有独立代理", profiles: "代理列表", add: "添加代理", empty: "还没有代理配置", newProfile: "新建代理", newEyebrow: "NEW PROXY", editEyebrow: "EDIT PROXY", name: "代理名称", url: "代理地址", type: "代理类型", hostname: "代理主机", port: "端口", username: "代理用户名（可选）", password: "代理密码（可选）", credentialsHint: "支持 HTTP、HTTPS、SOCKS4、SOCKS4A、SOCKS5 和 SOCKS5H。SOCKS4/4A 暂不支持认证；SOCKS4A/SOCKS5H 由代理端解析 DNS。密码保存在系统凭据管理器中。", saveProfile: "保存代理", remove: "删除" },
    proxyErrors: { proxiesRead: "无法读取代理配置", proxiesFormat: "代理配置文件格式错误", proxiesSave: "无法保存代理配置", proxyMissing: "代理配置不存在", proxyInUse: "该代理正被全局设置或 Registry 使用，无法删除", invalidProxyName: "代理名称不能为空", invalidProxyUrl: "代理地址无效，仅支持 HTTP、HTTPS 或 SOCKS", proxyAuthUnsupported: "SOCKS4 和 SOCKS4A 不支持用户名密码认证" },
    presets: { title: "常用公共 Registry", subtitle: "选择后将以匿名方式直接添加，认证信息可稍后配置。", custom: "或配置自建 Registry", added: "已添加 {name}" },
    confirm: { title: "删除 {tag}？", bodyBefore: "将删除", bodyAfter: "对应的 Manifest。此操作无法通过本应用撤销。", action: "确认删除" },
    toast: { updated: "连接已更新", added: "Registry 已添加", removed: "连接已移除", registryOrderSaved: "Registry 顺序已保存", proxySaved: "代理设置已保存", proxyRemoved: "代理已删除", manifestDeleted: "Manifest 已删除", refreshing: "正在刷新数据", pullCopied: "Pull 命令已复制", imageNameCopied: "镜像名已复制", tagCopied: "Tag 已复制", referenceCopied: "完整镜像引用已复制", digestCopied: "Digest 已复制", logsCopied: "同步日志已复制" },
    validation: { required: "请填写名称和地址", protocol: "地址必须以 http:// 或 https:// 开头", allowHttp: "使用 HTTP 时需启用“允许不安全 HTTP”", proxyName: "请输入代理名称", proxyRequired: "请选择代理配置", proxyAddress: "请输入有效的代理主机和 1 至 65535 之间的端口", proxyUrl: "请输入有效的 HTTP、HTTPS 或 SOCKS 代理地址，用户名和密码请使用独立字段" },
    sync: { action: "同步镜像", eyebrow: "REGISTRY TRANSFER", title: "同步镜像", source: "来源", target: "目标 Registry", targetRepository: "目标仓库", selectSourceRepository: "选择来源仓库", privateTargetsOnly: "暂时仅支持同步到私有 Registry", noPrivateTarget: "请先添加一个私有 Registry 作为同步目标", platform: "同步平台", platformDefault: "默认", allPlatforms: "全部平台", customPlatform: "自定义平台", architecture: "架构", singlePlatformHint: "只同步匹配平台的 Manifest 和 Blob，目标 Tag 将成为单平台镜像。", allPlatformsHint: "同步完整的多平台 Index 及其全部 Manifest 和 Blob。", selectTags: "选择 Tags", selectedCount: "已选择 {count} 个", selectVisible: "选择当前结果", clearVisible: "取消当前结果", note: "目标端已有的 Blob 会自动跳过；下载的 Blob 会按摘要缓存以供后续同步复用。", ready: "准备同步 {count} 个 Tag", start: "开始同步", syncing: "正在同步", stop: "停止同步", stopping: "正在停止", completed: "已同步 {tags} 个 Tag，复制 {copied} 个 Blob，跳过 {skipped} 个，缓存命中 {cached} 个", status: { idle: "等待开始", running: "同步进行中", stopping: "正在停止同步", success: "同步完成", error: "同步失败", cancelled: "同步已停止" }, stages: { prepare: "初始化源和目标连接", manifests: "读取并解析 Manifest", blobs: "检查并传输 Blob", manifestsWrite: "写入目标 Manifest", tags: "发布目标 Tag", complete: "完成" }, waiting: "等待前序步骤", progressHint: "正在执行同步任务，详细请求记录会显示在下方。", logs: "详细日志", copyLogs: "复制日志", logFile: "日志文件", back: "返回修改", close: "关闭", resultSummary: "{tags} 个 Tag，复制 {copied} 个 Blob，跳过 {skipped} 个，缓存命中 {cached} 个，共上传 {bytes}", validationSource: "请选择来源 Registry", validationSourceRepository: "请选择来源仓库", validationTarget: "请选择目标 Registry", validationRepository: "请填写目标仓库", validationTags: "请至少选择一个 Tag", validationPlatform: "请填写平台的 OS 和架构" },
    syncBatch: { singleMode: "单个镜像", batchMode: "批量同步", repositoryCount: "已选择 {count} 个镜像", selectVisibleRepositories: "选择当前镜像", clearVisibleRepositories: "取消当前镜像", selectRepository: "请先选择一个镜像并配置 Tags", ready: "已选择 {repositories} 个镜像、{tags} 个 Tag", validationRepositories: "请至少选择一个镜像", validationTags: "请为每个已选镜像至少选择一个 Tag", currentImage: "当前同步镜像", complete: "全部处理完成", total: "总数", succeeded: "成功", failed: "失败", remaining: "剩余", failedImages: "失败的镜像", partial: "批量同步部分完成", partialCompleted: "批量同步完成：成功 {succeeded} 个，失败 {failed} 个", retryFailed: "重试失败项 ({count})" },
    syncBatchErrors: { syncBatchSelectionRequired: "请至少选择一个镜像，并为每个镜像选择 Tag" },
    syncWindow: { maximize: "最大化", restore: "还原" },
    syncErrors: { invalidSyncOperation: "同步任务 ID 无效", invalidSyncPlatform: "同步平台格式无效", syncPlatformNotFound: "所选 Tag 不包含指定平台", syncCancelled: "同步已停止", syncLogCreate: "无法创建同步日志文件", syncTempCreate: "无法创建同步临时目录", syncTempWrite: "无法写入 Blob 临时文件", syncTempRead: "无法读取 Blob 临时文件", syncCacheCreate: "无法创建 Blob 缓存", syncCacheRead: "无法读取 Blob 缓存", syncCacheWrite: "无法写入 Blob 缓存", syncCacheDigest: "Blob 缓存摘要校验失败" },
    errors: { unknown: "发生未知错误", detail: "详情：{detail}" },
    backend: { configDir: "无法创建配置目录", keyring: "无法访问系统凭据管理器", credentialsRead: "无法读取 Registry 凭据", settingsRead: "无法读取连接配置", settingsFormat: "连接配置格式错误", settingsSave: "无法保存连接配置", appSettingsRead: "无法读取全局设置", appSettingsFormat: "全局设置格式错误", appSettingsSave: "无法保存全局设置", invalidUrl: "Registry 地址无效", scheme: "Registry 地址仅支持 HTTP 或 HTTPS", httpDisabled: "请明确启用允许不安全 HTTP", invalidRegistry: "Registry 名称或地址无效", invalidRepository: "仓库名称无效，请不要包含 Registry 地址、Tag 或 Digest", invalidProxyUrl: "代理地址无效，仅支持 HTTP 或 HTTPS", invalidProxyMode: "Registry 代理模式无效", proxyCredentialsInUrl: "请不要在代理地址中包含用户名或密码", proxyCredentialsClear: "无法清理旧代理凭据", proxyCredentialsSave: "无法保存代理凭据", proxyCredentialsDelete: "连接已移除，但代理凭据删除失败", credentialsClear: "无法清理旧 Registry 凭据", credentialsSave: "无法保存 Registry 凭据", credentialsDelete: "连接已移除，但系统凭据删除失败", registryMissing: "Registry 连接不存在", caRead: "无法读取自定义 CA 文件", caFormat: "CA 文件格式无效", client: "无法创建 HTTP 客户端", bearerChallenge: "Bearer 认证信息缺少 realm", tokenFormat: "Token 响应格式无效", tokenMissing: "Token 响应中缺少 token", catalogFormat: "仓库目录响应格式无效", tagsFormat: "标签响应格式无效", manifestRead: "读取 Manifest 内容失败", manifestFormat: "Manifest 格式无效", imageConfigFormat: "镜像配置格式无效", timeout: "连接 Registry 超时", connect: "无法连接 Registry", request: "Registry 请求失败", auth: "认证失败，请检查用户名、密码或访问权限", forbidden: "当前账号没有执行该操作的权限", notFound: "资源不存在，或 Registry 未开放此接口", deleteDisabled: "Registry 未启用 Manifest 删除功能", registryError: "Registry 返回错误", syncTagsRequired: "请至少选择一个 Tag", syncRepositoryRequired: "来源仓库和目标仓库不能为空", syncPublicTargetUnsupported: "暂时不支持同步到公共 Registry", manifestMissing: "同步所需的 Manifest 不完整", blobRead: "读取镜像 Blob 失败", uploadLocation: "Registry 返回的上传地址无效" },
  },
  en: {
    common: { retry: "Retry", cancel: "Cancel", unknown: "Unknown", repository: "repository" },
    nav: { registries: "REGISTRIES", addRegistry: "Add registry", addFirst: "Add your first registry", settings: "Connection settings", globalSettings: "Global proxy settings", language: "Change language", moveUp: "Move up", moveDown: "Move down" },
    connection: { checking: "Checking", connected: "Connected", failed: "Connection issue" },
    welcome: { eyebrow: "PRIVATE REGISTRY MANAGER", title: "Connect your image registry", body: "Browse repositories, tags, and manifests, then clean up images with confidence." },
    repositories: { eyebrow: "CATALOG", title: "Repositories", search: "Search repositories", loading: "Loading repositories", error: "Unable to read catalog", empty: "No repositories found", publicEmpty: "Add a full repository name to browse its images", add: "Add repository", removeHint: "Remove from Kaven Docker list", removed: "Removed repository {repository} from Kaven Docker", addTitle: "Add image repositories", addMethod: "Add method", discoverMode: "Discover", manualMode: "Enter manually", namespace: "User or namespace", discover: "Discover repositories now", additionalNames: "Additional repository names (optional)", fullNames: "Full repository names", namesPlaceholder: "api\nweb\nworker", addHint: "Repositories are discovered automatically after you enter a namespace. You can also enter extra names one per line, or a full name such as {example}.", manualHint: "Enter one full name per line or separate names with commas. For example: {example}. Do not include the Registry host, tag, or digest.", discoveryUnsupported: "This Registry cannot discover repositories by namespace; switch to manual entry.", discovered: "Found {count} repositories", preview: "Repositories to add", selected: "{count} selected", selectAll: "Select all", deselectAll: "Deselect all", saveCount: "Add {count}", required: "Select at least one repository", addedMany: "Added {count} repositories" },
    discoveryErrors: { invalidNamespace: "The user or namespace is invalid", repositoryDiscoveryUnsupported: "This Registry does not support repository discovery", repositoryDiscoveryAuthRequired: "GHCR discovery requires a configured GitHub token with read:packages access", repositoryDiscoveryFormat: "The repository discovery API returned invalid data" },
    registryOrderErrors: { invalidRegistryOrder: "The Registry order is invalid; refresh and try again" },
    tags: { eyebrow: "VERSIONS", title: "Tags", search: "Search tags", loading: "Loading tags", error: "Unable to read tags", selectRepository: "Select a repository", empty: "No tags found" },
    details: { loading: "Parsing manifest", error: "Unable to load manifest", eyebrow: "IMAGE DETAILS", more: "More actions", copyPull: "Copy pull command", reference: "Image reference", imageName: "Image name", copyImageName: "Copy image name", tag: "Tag", copyTag: "Copy tag", fullReference: "Full reference", copyReference: "Copy full image reference", imageSize: "Image size", platforms: "Platforms", platformCount: "{count} platforms", created: "Created", manifest: "Manifest", digest: "Digest", copyDigest: "Copy digest", mediaType: "Media type", layers: "Layers", labels: "Labels", selectTitle: "Select an image tag", selectBody: "Manifest, platform, and layer details will appear here." },
    danger: { title: "Delete manifest", hint: "Server-side garbage collection is required to reclaim storage.", action: "Delete" },
    form: { eyebrow: "REGISTRY CONNECTION", editTitle: "Edit connection", addTitle: "Add registry", displayName: "Display name", address: "Registry URL", auth: "Authentication", anonymous: "Anonymous", basic: "Username & password", username: "Username", password: "Password", keepPassword: "Leave blank to keep current password", enterPassword: "Enter password", caPath: "Custom CA file path (optional)", allowHttp: "Allow insecure HTTP", allowHttpHint: "Use only on a trusted network", skipTls: "Skip TLS certificate verification", skipTlsHint: "Not recommended for production", timeout: "Request timeout", seconds: "seconds", uploadChunkSize: "Upload chunk size", uploadChunkSizeHint: "Larger chunks reduce target Registry state-file writes. Allowed range: 1–256 MiB.", remove: "Remove connection", save: "Save connection" },
    proxy: { eyebrow: "NETWORK SETTINGS", globalTitle: "Proxy profiles", globalDefault: "Global default proxy", applyDefault: "Apply default", registryMode: "Proxy settings", followGlobal: "Follow global settings", direct: "Direct connection (no proxy)", savedProfiles: "Saved proxies", legacyCustom: "Existing custom proxy", profiles: "Proxy profiles", add: "Add proxy", empty: "No proxy profiles yet", newProfile: "New proxy", newEyebrow: "NEW PROXY", editEyebrow: "EDIT PROXY", name: "Proxy name", url: "Proxy URL", type: "Proxy type", hostname: "Proxy hostname", port: "Port", username: "Proxy username (optional)", password: "Proxy password (optional)", credentialsHint: "Supports HTTP, HTTPS, SOCKS4, SOCKS4A, SOCKS5, and SOCKS5H. Authentication is unavailable for SOCKS4/4A; SOCKS4A/SOCKS5H resolve DNS through the proxy. Passwords stay in the system credential manager.", saveProfile: "Save proxy", remove: "Delete" },
    proxyErrors: { proxiesRead: "Unable to read proxy profiles", proxiesFormat: "The proxy profiles file is invalid", proxiesSave: "Unable to save proxy profiles", proxyMissing: "The proxy profile does not exist", proxyInUse: "This proxy is used by the global default or a Registry and cannot be deleted", invalidProxyName: "The proxy name is required", invalidProxyUrl: "The proxy URL is invalid; only HTTP, HTTPS, and SOCKS are supported", proxyAuthUnsupported: "SOCKS4 and SOCKS4A do not support username/password authentication" },
    presets: { title: "Popular public registries", subtitle: "Select one to add it anonymously. Credentials can be configured later.", custom: "or configure a self-hosted Registry", added: "Added {name}" },
    confirm: { title: "Delete {tag}?", bodyBefore: "This will delete the manifest for", bodyAfter: ". This action cannot be undone in this app.", action: "Delete manifest" },
    toast: { updated: "Connection updated", added: "Registry added", removed: "Connection removed", registryOrderSaved: "Registry order saved", proxySaved: "Proxy settings saved", proxyRemoved: "Proxy deleted", manifestDeleted: "Manifest deleted", refreshing: "Refreshing data", pullCopied: "Pull command copied", imageNameCopied: "Image name copied", tagCopied: "Tag copied", referenceCopied: "Full image reference copied", digestCopied: "Digest copied", logsCopied: "Sync logs copied" },
    validation: { required: "Enter a name and URL", protocol: "The URL must start with http:// or https://", allowHttp: "Enable “Allow insecure HTTP” to use an HTTP URL", proxyName: "Enter a proxy name", proxyRequired: "Select a proxy profile", proxyAddress: "Enter a valid proxy hostname and a port from 1 to 65535", proxyUrl: "Enter a valid HTTP, HTTPS, or SOCKS proxy URL and use the separate credential fields" },
    sync: { action: "Sync images", eyebrow: "REGISTRY TRANSFER", title: "Sync images", source: "Source", target: "Target Registry", targetRepository: "Target repository", selectSourceRepository: "Select source repository", privateTargetsOnly: "Public registries are not available as targets yet", noPrivateTarget: "Add a private Registry to use as the sync target", platform: "Sync platform", platformDefault: "default", allPlatforms: "All platforms", customPlatform: "Custom platform", architecture: "Architecture", singlePlatformHint: "Only the matching manifest and blobs are synced. The target tag becomes a single-platform image.", allPlatformsHint: "Sync the complete multi-platform index and all referenced manifests and blobs.", selectTags: "Select tags", selectedCount: "{count} selected", selectVisible: "Select visible", clearVisible: "Clear visible", note: "Blobs already present at the target are skipped. Downloaded blobs are cached by digest for later syncs.", ready: "Ready to sync {count} tags", start: "Start sync", syncing: "Syncing", stop: "Stop sync", stopping: "Stopping", completed: "Synced {tags} tags, copied {copied} blobs, skipped {skipped}, {cached} cache hits", status: { idle: "Ready", running: "Sync in progress", stopping: "Stopping sync", success: "Sync complete", error: "Sync failed", cancelled: "Sync stopped" }, stages: { prepare: "Initialize source and target", manifests: "Read and resolve manifests", blobs: "Check and transfer blobs", manifestsWrite: "Write target manifests", tags: "Publish target tags", complete: "Complete" }, waiting: "Waiting for the previous step", progressHint: "The sync is running. Detailed request logs appear below.", logs: "Detailed logs", copyLogs: "Copy logs", logFile: "Log file", back: "Back to settings", close: "Close", resultSummary: "{tags} tags, {copied} blobs copied, {skipped} skipped, {cached} cache hits, {bytes} uploaded", validationSource: "Select a source Registry", validationSourceRepository: "Select a source repository", validationTarget: "Select a target Registry", validationRepository: "Enter a target repository", validationTags: "Select at least one tag", validationPlatform: "Enter a platform OS and architecture" },
    syncBatch: { singleMode: "Single image", batchMode: "Batch sync", repositoryCount: "{count} images selected", selectVisibleRepositories: "Select visible images", clearVisibleRepositories: "Clear visible images", selectRepository: "Select an image and configure its tags", ready: "{repositories} images and {tags} tags selected", validationRepositories: "Select at least one image", validationTags: "Select at least one tag for every selected image", currentImage: "Current image", complete: "All images processed", total: "Total", succeeded: "Succeeded", failed: "Failed", remaining: "Remaining", failedImages: "Failed images", partial: "Batch sync partially completed", partialCompleted: "Batch sync completed: {succeeded} succeeded, {failed} failed", retryFailed: "Retry failed ({count})" },
    syncBatchErrors: { syncBatchSelectionRequired: "Select at least one image and tags for every image" },
    syncWindow: { maximize: "Maximize", restore: "Restore" },
    syncErrors: { invalidSyncOperation: "The sync operation ID is invalid", invalidSyncPlatform: "The sync platform is invalid", syncPlatformNotFound: "The selected tag does not contain the requested platform", syncCancelled: "Sync stopped", syncLogCreate: "Unable to create the sync log file", syncTempCreate: "Unable to create the sync temporary directory", syncTempWrite: "Unable to write the temporary blob file", syncTempRead: "Unable to read the temporary blob file", syncCacheCreate: "Unable to create the blob cache", syncCacheRead: "Unable to read the blob cache", syncCacheWrite: "Unable to write the blob cache", syncCacheDigest: "Blob cache digest verification failed" },
    errors: { unknown: "An unknown error occurred", detail: "Details: {detail}" },
    backend: { configDir: "Unable to create the settings directory", keyring: "Unable to access the system credential manager", credentialsRead: "Unable to read Registry credentials", settingsRead: "Unable to read connection settings", settingsFormat: "The connection settings file is invalid", settingsSave: "Unable to save connection settings", appSettingsRead: "Unable to read global settings", appSettingsFormat: "The global settings file is invalid", appSettingsSave: "Unable to save global settings", invalidUrl: "The Registry URL is invalid", scheme: "The Registry URL must use HTTP or HTTPS", httpDisabled: "Enable insecure HTTP to use this URL", invalidRegistry: "The Registry name or URL is invalid", invalidRepository: "The repository name is invalid. Do not include a Registry host, tag, or digest", invalidProxyUrl: "The proxy URL is invalid; only HTTP and HTTPS are supported", invalidProxyMode: "The Registry proxy mode is invalid", proxyCredentialsInUrl: "Do not include credentials in the proxy URL", proxyCredentialsClear: "Unable to clear old proxy credentials", proxyCredentialsSave: "Unable to save proxy credentials", proxyCredentialsDelete: "The connection was removed, but its proxy credentials could not be deleted", credentialsClear: "Unable to clear old Registry credentials", credentialsSave: "Unable to save Registry credentials", credentialsDelete: "The connection was removed, but its credentials could not be deleted", registryMissing: "The Registry connection does not exist", caRead: "Unable to read the custom CA file", caFormat: "The CA file is invalid", client: "Unable to create the HTTP client", bearerChallenge: "The Bearer challenge does not include a realm", tokenFormat: "The token response is invalid", tokenMissing: "The token response does not include a token", catalogFormat: "The catalog response is invalid", tagsFormat: "The tag response is invalid", manifestRead: "Unable to read the manifest body", manifestFormat: "The manifest is invalid", imageConfigFormat: "The image configuration is invalid", timeout: "Registry connection timed out", connect: "Unable to connect to the Registry", request: "The Registry request failed", auth: "Authentication failed. Check the username, password, and permissions", forbidden: "This account is not allowed to perform this action", notFound: "The resource does not exist or this Registry API is unavailable", deleteDisabled: "Manifest deletion is not enabled on this Registry", registryError: "The Registry returned an error", syncTagsRequired: "Select at least one tag", syncRepositoryRequired: "Source and target repositories are required", syncPublicTargetUnsupported: "Syncing to a public Registry is not supported yet", manifestMissing: "A required manifest is missing from the sync graph", blobRead: "Unable to read an image blob", uploadLocation: "The Registry returned an invalid upload URL" },
  },
} as const;

export type AppLocale = keyof typeof messages;
const savedLocale = localStorage.getItem("kaven-docker.locale");
const initialLocale: AppLocale = savedLocale === "en" ? "en" : "zh-CN";

export const i18n = createI18n({
  legacy: false,
  locale: initialLocale,
  fallbackLocale: "en",
  messages,
});
